networks:
  default: mainnet-fork

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.0.0

compiler:
  solc:
    version: 0.8.0
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0"

autofetch_sources: true